
import { Roboto } from "next/font/google";
import './global.css';
import { Header } from "./store/components/shared/Header";
import { Footer } from "./store/components/shared/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
})

// export const metadata: Metadata = {
//   title: "Future world",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      

      <body
        className={`${roboto.variable} ${roboto.variable} antialiased`}
      >
        <Header />


        {children}
        <Footer />
      </body>
      
    </html>
  );
}
