
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "./store/components/shared/Header";
import { Footer } from "./store/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Future world",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <Header />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        {children}
      </body>
      <Footer />
    </html>
  );
}
